######################################################################
# Automatically generated by qmake (2.01a) mer. janv. 12 23:10:59 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network
RESOURCES = application.qrc

# Input
HEADERS += MainWindow.h \
    SettingsWindow.h Protocol.h
SOURCES += main.cpp MainWindow.cpp \
    SettingsWindow.cpp
