sudo: required

language: cpp

services:
  - docker

env:
  - PROJECT=server
  - PROJECT=client

before_install:
  - docker pull archlinux/base
  - docker run -e BUILD_DIR=$PROJECT -itd --name build archlinux/base
  - docker exec build pacman -Syyu --noconfirm
  - docker exec build pacman -S --noconfirm base-devel clang git qbs qt5 ogre
  - docker exec build git clone https://github.com/7185/pimak-worlds

script:
  - docker exec build qbs --version
  - docker exec build qbs setup-toolchains --detect
  - docker exec build qbs setup-qt --detect
  - docker exec build qbs config defaultProfile qt-5-11-1
  - docker exec build /bin/sh -c 'cd pimak-worlds/$BUILD_DIR; qbs build -d build/'
