dist: trusty
sudo: required

language: cpp

before_install:
  - sudo apt-get install -qq qt5-qmake qtbase5-dev libogre-1.9-dev

env:
  - PROJECT=server
  - PROJECT=client

script:
  - cd $PROJECT
  - qmake -qt=qt5
  - make

