######################################################################
# Automatically generated by qmake (2.01a) mer. janv. 12 14:10:48 2011
######################################################################

QT     += network
QT     -= gui
CONFIG += c++11

TARGET = pwserver
TEMPLATE = app

DEPENDPATH += .
INCLUDEPATH += . include ../common/include

# Input
HEADERS += include/*.h
HEADERS += ../common/include/*.h
SOURCES += src/*.cpp
