######################################################################
# Automatically generated by qmake (2.01a) mer. janv. 12 14:10:48 2011
######################################################################

QT     += network
QT     -= gui
CONFIG += c++11

TARGET = pwserver
TEMPLATE = app

DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Server.h \
    Client.h Protocol.h
SOURCES += Server.cpp main.cpp \
    Client.cpp
